# Generated by Django 2.0.1 on 2018-01-13 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_owner', models.CharField(max_length=30)),
                ('asset_custodian', models.CharField(max_length=30)),
                ('asset_name', models.CharField(max_length=30)),
                ('asset_desc', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('date_eol', models.DateTimeField(verbose_name='end of life')),
            ],
        ),
        migrations.CreateModel(
            name='SystemAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_owner', models.CharField(max_length=30)),
                ('asset_custodian', models.CharField(max_length=30)),
                ('asset_name', models.CharField(max_length=30)),
                ('asset_desc', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('parent_hardware', models.ManyToManyField(to='hwam.HardwareAsset')),
                ('parent_systems', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hwam.SystemAsset')),
            ],
        ),
    ]
