# Generated by Django 2.0.1 on 2018-01-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemasset',
            name='parent_hardware',
            field=models.ManyToManyField(null=True, to='hwam.HardwareAsset'),
        ),
    ]
