# Generated by Django 2.0.4 on 2018-04-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwam', '0002_auto_20180328_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareasset',
            name='ip4_address_5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='ip4_address_6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='ip4_address_7',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='ip4_address_8',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='ip6_address_5',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='ip6_address_6',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='ip6_address_7',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='ip6_address_8',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='package_vendor',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
