# Generated by Django 2.0.1 on 2018-01-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwam', '0002_auto_20180113_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemasset',
            name='parent_hardware',
            field=models.ManyToManyField(to='hwam.HardwareAsset'),
        ),
    ]
