# Generated by Django 2.0.1 on 2018-01-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwam', '0003_auto_20180113_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemasset',
            name='parent_systems',
        ),
        migrations.AddField(
            model_name='systemasset',
            name='parent_systems',
            field=models.ManyToManyField(related_name='_systemasset_parent_systems_+', to='hwam.SystemAsset'),
        ),
    ]
