facility_choices = (
        (0, ("kern")),
        (1, ("user")),
        (2, ("mail")),
        (3, ("daemon")),
        (4, ("auth")),
        (5, ("syslog")),
        (6, ("lpr")),
        (7, ("news")),
        (8, ("uucp")),
        (9, ("clock")),
        (10, ("authpriv")),
        (11, ("ftp")),
        (12, ("-")),
        (13, ("-")),
        (14, ("-")),
        (15, ("cron")),
        (16, ("local0")),
        (17, ("local1")),
        (18, ("local2")),
        (19, ("local3")),
        (20, ("local4")),
        (21, ("local5")),
        (22, ("local6")),
        (23, ("local7")),
)
severity_choices = (
        (0, ("emerg")),
        (1, ("alert")),
        (2, ("crit")),
        (3, ("err")),
        (4, ("warning")),
        (5, ("notice")),
        (6, ("info")),
        (7, ("debug")),
)
