
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'risk'
urlpatterns = [
    path('', views.index, name='index'),
    path('ate/', views.ATEIndexView.as_view(), name='ate_index'),
    path('nte/', views.NTEIndexView.as_view(), name='nte_index'),
    path('ats/', views.ATSIndexView.as_view(), name='ats_index'),
    path('nts/', views.NTSIndexView.as_view(), name='nts_index'),
    path('vuln/', views.VulnIndexView.as_view(), name='vuln_index'),
    path('cond/', views.CondIndexView.as_view(), name='cond_index'),
    path('impact/', views.ImpactIndexView.as_view(), name='impact_index'),
    path('ate/<int:pk>/', views.ATEDetailView.as_view(), name='ate_detail'),
    path('nte/<int:pk>/', views.NTEDetailView.as_view(), name='nte_detail'),
    path('ats/<int:pk>/', views.ATSDetailView.as_view(), name='ats_detail'),
    path('nts/<int:pk>/', views.NTSDetailView.as_view(), name='nts_detail'),
    path('vuln/<int:pk>/', views.VulnDetailView.as_view(),
        name='vuln_detail'),
    path('cond/<int:pk>/', views.CondDetailView.as_view(),
        name='cond_detail'),
    path('impact/<int:pk>/', views.ImpactDetailView.as_view(),
        name='impact_detail'),
    path('ate/add/', login_required(views.ATECreateView.as_view()),
        name='ate_create'),
    path('nte/add/', login_required(views.NTECreateView.as_view()),
        name='nte_create'),
    path('ats/add/', login_required(views.ATSCreateView.as_view()),
        name='ats_create'),
    path('nts/add/', login_required(views.NTSCreateView.as_view()),
        name='nts_create'),
    path('vuln/add/', login_required(views.VulnCreateView.as_view()),
        name='vuln_create'),
    path('cond/add/', login_required(views.CondCreateView.as_view()),
        name='cond_create'),
    path('impact/add/', login_required(views.ImpactCreateView.as_view()),
        name='impact_create'),
    path('ate/<int:pk>/update/',
        login_required(views.ATEUpdateView.as_view()),
        name='ate_update'),
    path('nte/<int:pk>/update/',
        login_required(views.NTEUpdateView.as_view()),
        name='nte_update'),
    path('ats/<int:pk>/update/',
        login_required(views.ATSUpdateView.as_view()),
        name='ats_update'),
    path('nts/<int:pk>/update/',
        login_required(views.NTSUpdateView.as_view()),
        name='nts_update'),
    path('vuln/<int:pk>/update/',
        login_required(views.VulnUpdateView.as_view()),
        name='vuln_update'),
    path('cond/<int:pk>/update/',
        login_required(views.CondUpdateView.as_view()),
        name='cond_update'),
    path('impact/<int:pk>/update/',
        login_required(views.ImpactUpdateView.as_view()),
        name='impact_update'),
    #path('vuln/', views.VLIndexView.as_view(), name='vl_index'),
    #path('cond/', views.CNIndexView.as_view(), name='cn_index'),
    #path('vuln/<int:pk>/', views.VLDetailView.as_view(), name='vl_detail'),
    #path('cond/<int:pk>/', views.CNDetailView.as_view(), name='cn_detail'),
]

