# Generated by Django 2.0.1 on 2018-02-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0002_auto_20180209_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitrule',
            name='dest_port_filter',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='limitrule',
            name='source_port_filter',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
