# Generated by Django 2.0.1 on 2018-02-21 02:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siem', '0004_auto_20180211_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitrule',
            name='alert_users',
            field=models.ManyToManyField(blank=True, related_name='alert_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='limitrule',
            name='email_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logevent',
            name='byte_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logevent',
            name='class_of_service',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logevent',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logevent',
            name='interface',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='logevent',
            name='packet_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logevent',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logevent',
            name='tcp_flags',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsehelper',
            name='helper_type',
            field=models.CharField(default='default', max_length=32),
            preserve_default=False,
        ),
    ]
