# Generated by Django 2.0.1 on 2018-02-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0005_auto_20180220_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitrule',
            name='action_filter',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='limitrule',
            name='interface_filter',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='limitrule',
            name='source_user_filter',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='limitrule',
            name='target_user_filter',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='limitrule',
            name='process_filter',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
