# Generated by Django 2.0.1 on 2018-02-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0007_auto_20180221_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logevent',
            name='start_time',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
