# Generated by Django 2.0.1 on 2018-02-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0008_auto_20180222_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logevent',
            name='duration',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
