# Generated by Django 2.0.3 on 2018-03-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0010_auto_20180312_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleevent',
            name='dest_host_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruleevent',
            name='source_host_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
