# Generated by Django 2.0.3 on 2018-03-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0012_auto_20180318_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limitrule',
            old_name='referer_filter_regex',
            new_name='referrer_filter_regex',
        ),
    ]
