# Generated by Django 2.0.3 on 2018-03-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0014_auto_20180318_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitrule',
            name='is_builtin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='limitrule',
            name='status_filter_regex',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='logevent',
            name='status',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='logeventparser',
            name='is_builtin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parsehelper',
            name='is_builtin',
            field=models.BooleanField(default=False),
        ),
    ]
