# Generated by Django 2.0.3 on 2018-03-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0015_auto_20180326_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logeventparser',
            options={'permissions': (('view_logeventparser', 'Can view log event parsers'),)},
        ),
        migrations.AlterModelOptions(
            name='parsehelper',
            options={'permissions': (('view_logeventparser', 'Can view log event parsers'),)},
        ),
        migrations.AlterField(
            model_name='limitrule',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='logeventparser',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='parsehelper',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='limitrule',
            unique_together={('name', 'is_builtin')},
        ),
        migrations.AlterUniqueTogether(
            name='logeventparser',
            unique_together={('name', 'is_builtin')},
        ),
        migrations.AlterUniqueTogether(
            name='parsehelper',
            unique_together={('name', 'is_builtin')},
        ),
    ]
