# Generated by Django 2.0.4 on 2018-04-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0016_auto_20180326_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitrule',
            name='match_field',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='limitrule',
            name='match_list_path',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
