# Generated by Django 2.0.4 on 2018-04-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0017_auto_20180409_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitrule',
            name='match_friendlist',
            field=models.BooleanField(default=False),
        ),
    ]
