# Generated by Django 2.0.4 on 2018-04-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0018_limitrule_match_friendlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitrule',
            name='event_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
