# Generated by Django 2.0.4 on 2018-04-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0020_limitrule_reverse_logic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitrule',
            name='backup_lifespan_days',
            field=models.IntegerField(default=366),
        ),
        migrations.AlterField(
            model_name='limitrule',
            name='event_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='limitrule',
            name='local_lifespan_days',
            field=models.IntegerField(default=185),
        ),
        migrations.AlterField(
            model_name='limitrule',
            name='time_int',
            field=models.IntegerField(default=5),
        ),
    ]
