# Generated by Django 2.1.7 on 2019-03-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0025_auto_20181119_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limitrule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='logevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='logeventparser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parsehelper',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ruleevent',
            options={},
        ),
        migrations.AlterField(
            model_name='limitrule',
            name='is_builtin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='logeventparser',
            name='is_builtin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='parsehelper',
            name='is_builtin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterUniqueTogether(
            name='limitrule',
            unique_together=set(),
        ),
    ]
